With gg as

(select Gift.* from Gift
join CONSTIT_GIFTS_DC on CONSTIT_GIFTS_DC.Gift_ID = GIFT.ID),

tt as 

(SELECT 
 FUNDATTRIBUTES.TABLEENTRIESID "TABLEENTRIESID",
 FUNDATTRIBUTES.IMPORTID, 
FUNDATTRIBUTES.PARENTID, 
FUNDATTRIBUTES.ATTRIBUTEDATE, 
FUNDATTRIBUTES.COMMENTS, 
TABLEENTRIES.LongDESCRIPTION, 
TABLEENTRIES.SHORTDESCRIPTION, 
TABLEENTRIES.SEQUENCE

FROM 
DBO.FUNDATTRIBUTES LEFT OUTER JOIN DBO.TABLEENTRIES ON FUNDATTRIBUTES.TABLEENTRIESID = TABLEENTRIES.TABLEENTRIESID

WHERE 
ATTRIBUTETYPESID  =  414)  




SELECT 
 GIFT_RECORDS.CONSTITUENT_ID "Constituent ID",
 CASE WHEN GIFT_RECORDS.FIRST_NAME is NULL then GIFT_RECORDS.ORG_NAME ELSE CONCAT(GIFT_RECORDS.FIRST_NAME,' ',GIFT_RECORDS.LAST_NAME)
 END AS Name,
 GIFT_RECORDS.PRIMARY_ADDRESSEE "Primary Addressee",
-- DBO.Query_ConstitName(4,GIFT_RECORDS.LAST_NAME,GIFT_RECORDS.FIRST_NAME,GIFT_RECORDS.MIDDLE_NAME,GIFT_RECORDS.ORG_NAME,GIFT_RECORDS.KEY_INDICATOR,GIFT_RECORDS.CONSTITUENT_ID) "Name",
-- DBO.Query_GetAddrSal(GIFT_RECORDS.ID,GIFT_RECORDS.PRIMARY_ADDRESSEE_EDIT,GIFT_RECORDS.PRIMARY_ADDRESSEE_ID,GIFT_RECORDS.PRIMARY_ADDRESSEE,'04/30/2018') "Primary Addressee",
 convert(nvarchar(MAX), GIFT.DTE, 110)    "Gift Date",
CAST(GIFT_GiftSplit.Amount AS NUMERIC(18,2)) "Fund Split Amount",

 CASE GIFT.TYPE WHEN 1 THEN 'Cash' WHEN 2 THEN 'Pay-Cash' WHEN 3 THEN 'MG Pay-Cash' WHEN 8 THEN 'Pledge' WHEN 9 THEN 'Stock/Property' WHEN 10 THEN 'Stock/Property (Sold)' WHEN 11 THEN 'Pay-Stock/Property' WHEN 12 THEN 'MG Pay-Stock/Property' WHEN 13 THEN 'Pay-Stock/Property (Sold)' WHEN 14 THEN 'MG Pay-Stock/Property (Sold)' WHEN 15 THEN 'Gift-in-Kind' WHEN 16 THEN 'Pay-Gift-in-Kind' WHEN 17 THEN 'MG Pay-Gift-in-Kind' WHEN 18 THEN 'Other' WHEN 19 THEN 'Pay-Other' WHEN 20 THEN 'MG Pay-Other' WHEN 21 THEN 'Write Off' WHEN 22 THEN 'MG Write Off' WHEN 27 THEN 'MG Pledge' WHEN 30 THEN 'Recurring Gift' WHEN 31 THEN 'Recurring Gift Pay-Cash' WHEN 32 THEN 'GL Reversal' WHEN 33 THEN 'Amendment' WHEN 34 THEN 'Planned Gift' ELSE '' END  "Gift Type",
 GIFT_GiftSubType.LONGDESCRIPTION "Gift Subtype",
 GIFT_GiftSplit_FUND.FUND_ID "Fund ID",
 GIFT_GiftSplit_FUND.DESCRIPTION "Fund Description",
 GIFT_GiftSplit_APPEAL.APPEAL_ID "Appeal ID",
 GIFT_GiftSplit_APPEAL.DESCRIPTION "Appeal Description",
 T_3.LONGDESCRIPTION "Appeal Category",
 T_4_0_414.LONGDESCRIPTION "Fund Specific Attributes Fund Site Description",
 GIFT.UserGiftId "Gift ID",
-- DBO.Query_ConstitName(4,GIFT_RECORDS.LAST_NAME,GIFT_RECORDS.FIRST_NAME,GIFT_RECORDS.MIDDLE_NAME,GIFT_RECORDS.ORG_NAME,GIFT_RECORDS.KEY_INDICATOR,GIFT_RECORDS.CONSTITUENT_ID) "Sort Key",
 GIFT_RECORDS.LAST_NAME "Last Name",
 T_2.FIRST_NAME "First Name",
 GIFT_RECORDS.ORG_NAME "Organization Name",
 GIFT.ID "QRECID"

FROM 
gg AS GIFT 
INNER JOIN DBO.RECORDS AS GIFT_RECORDS ON GIFT.CONSTIT_ID = GIFT_RECORDS.ID 
LEFT OUTER JOIN DBO.CONSTITUENT_CODES AS T_1 ON GIFT_RECORDS.ID = T_1.CONSTIT_ID 
LEFT OUTER JOIN DBO.GIFTSPLIT AS GIFT_GiftSplit ON GIFT.ID = GIFT_GiftSplit.GIFTID 
LEFT OUTER JOIN DBO.APPEAL AS GIFT_GiftSplit_APPEAL ON GIFT_GiftSplit.APPEALID = GIFT_GiftSplit_APPEAL.ID 
LEFT OUTER JOIN DBO.SEARCHNAME AS T_2 ON GIFT_RECORDS.ID = T_2.RECORDS_ID 
LEFT OUTER JOIN DBO.TABLEENTRIES AS GIFT_GiftSubType ON GIFT.GiftSubType = GIFT_GiftSubType.TABLEENTRIESID 
LEFT OUTER JOIN DBO.FUND AS GIFT_GiftSplit_FUND ON GIFT_GiftSplit.FUNDID = GIFT_GiftSplit_FUND.ID 
LEFT OUTER JOIN DBO.TABLEENTRIES AS T_3 ON GIFT_GiftSplit_APPEAL.APPEALCATEGORYID = T_3.TABLEENTRIESID 
LEFT OUTER JOIN tt AS T_4_0_414 ON GIFT_GiftSplit_FUND.ID = T_4_0_414.PARENTID

WHERE 
((GIFT.DTE >=  CAST('1/1/2007' AS DATETIME) AND GIFT.Amount > 0 AND GIFT.TYPE IN ('1','3','8','18','20','31','34') AND T_1.CODE IN (317,312,16873,16466,17852,17853,17854,297,7841,7842,20214,20314,17015,20570,16461,20569,15760,16465,307,7843) AND GIFT_GiftSplit_APPEAL.AppealCategoryID IN (7705,2762,8670,8709,8710,16454,15895,17196) AND  NOT EXISTS (SELECT 
 GIFT_GiftSplit_APPEAL.APPEAL_ID "Appeal ID" FROM 
gg AS X_GIFT LEFT OUTER JOIN DBO.GIFTSPLIT AS GIFT_GiftSplit ON X_GIFT.ID = GIFT_GiftSplit.GIFTID LEFT OUTER JOIN DBO.APPEAL AS GIFT_GiftSplit_APPEAL ON GIFT_GiftSplit.APPEALID = GIFT_GiftSplit_APPEAL.ID WHERE 
(X_GIFT.ID  =  GIFT.ID)   AND (GIFT_GiftSplit_APPEAL.APPEAL_ID IN ('-TRIBUTE')))) AND ((GIFT.TYPE NOT IN ('28','32','33') OR (GIFT.TYPE IS NULL))))  

ORDER BY 
T_2.KEY_NAME, T_2.FIRST_NAME, T_2.MIDDLE_NAME, GIFT.DTE DESC