SELECT 
 ORECORDS.CONSTITUENT_ID "Constituent ID",
 CASE WHEN ORECORDS.FIRST_NAME is NULL then ORECORDS.ORG_NAME ELSE CONCAT(ORECORDS.FIRST_NAME,' ',ORECORDS.LAST_NAME)
 END AS Name,
case when
 CHARINDEX(CHAR(13),OT_1.ADDRESS_BLOCK) > 0  then
  Rtrim(Left(OT_1.address_block,CHARINDEX(CHAR(13),OT_1.ADDRESS_BLOCK)-1))
  else OT_1.ADDRESS_BLOCK end "Preferred Address Line 1" ,

  case when CHARINDEX(CHAR(13),OT_1.ADDRESS_BLOCK) > 0  then
  replace(replace(Rtrim(SUBSTRING(OT_1.ADDRESS_BLOCK,CHARINDEX(CHAR(10),OT_1.ADDRESS_BLOCK)+1,CHARINDEX(CHAR(10),OT_1.ADDRESS_BLOCK,CHARINDEX(Char(10),OT_1.ADDRESS_BLOCK)-1))),CHAR(13), ' '),CHAR(10), '')

  else NULL end "Preferred Address Line 2",

-- DBO.Query_ConstitName(4,ORECORDS.LAST_NAME,ORECORDS.FIRST_NAME,ORECORDS.MIDDLE_NAME,ORECORDS.ORG_NAME,ORECORDS.KEY_INDICATOR,ORECORDS.CONSTITUENT_ID) "Name",
-- DBO.ADDRESSLINE(1,OT_1.ADDRESS_BLOCK) "Preferred Address Line 1",
-- DBO.ADDRESSLINE(2,OT_1.ADDRESS_BLOCK) "Preferred Address Line 2",
 OT_1.CITY "Preferred City",
 OT_2.LONGDESCRIPTION "Preferred State",
 OT_1.POST_CODE "Preferred ZIP",
 OT_3.LONGDESCRIPTION "Preferred Country",
 ORECORDS.ID "QRECID"

FROM 
DBO.RECORDS AS ORECORDS INNER JOIN DBO.SEARCHNAME AS ORECORDS_SEARCHNAME ON ORECORDS.ID = ORECORDS_SEARCHNAME.RECORDS_ID INNER JOIN DBO.CAPREFERRED AS ORECORDS_CAPreferred ON ORECORDS.ID = ORECORDS_CAPreferred.CONSTIT_ID INNER JOIN DBO.ADDRESS AS OT_1 ON ORECORDS_CAPreferred.ADDRESS_ID = OT_1.ID LEFT OUTER JOIN DBO.STATES AS OT_2 ON OT_1.STATE = OT_2.SHORTDESCRIPTION LEFT OUTER JOIN DBO.TABLEENTRIES AS OT_3 ON OT_1.COUNTRY = OT_3.TABLEENTRIESID

WHERE 
((ORECORDS.IS_CONSTITUENT  =  -1))    AND EXISTS (SELECT 
 RECORDS.ID "QRECID" FROM 
DBO.RECORDS AS RECORDS INNER JOIN dbo.GIFT AS RECORDS_GIFT ON RECORDS.ID = RECORDS_GIFT.CONSTIT_ID 
INNER JOIN DBO.CONSTITUENT_CODES AS RECORDS_CONSTITUENT_CODES ON RECORDS.ID = RECORDS_CONSTITUENT_CODES.CONSTIT_ID INNER JOIN DBO.GIFTSPLIT AS RECORDS_GIFT_GiftSplit ON RECORDS_GIFT.ID = RECORDS_GIFT_GiftSplit.GIFTID INNER JOIN DBO.APPEAL AS T_1 ON RECORDS_GIFT_GiftSplit.APPEALID = T_1.ID WHERE 
((RECORDS_GIFT.DTE >=  CAST('1/1/2007' AS DATETIME) AND RECORDS_GIFT.Amount > 0 AND RECORDS_GIFT.TYPE IN ('1','8','3','18','20','30','34') AND RECORDS_CONSTITUENT_CODES.CODE IN (317,312,16873,16466,17852,17853,17854,297,7841,7842,20214,20314,17015,20570,16461,20569,15760,16465,307,7843) AND T_1.AppealCategoryID IN (7705,2762,8670,8709,8710,16454,15895,17196)))   AND ORECORDS.ID  =  RECORDS.ID)
--and ORECORDS.CONSTITUENT_ID = '417239'
ORDER BY 
ORECORDS_SEARCHNAME.KEY_NAME, ORECORDS_SEARCHNAME.FIRST_NAME, ORECORDS_SEARCHNAME.MIDDLE_NAME