SELECT 
 o.id "Records System ID",
 O.CONSTITUENT_ID "Constituent ID",
 O.FIRST_NAME,
 o.LAST_NAME,
 o.ORG_NAME,
 o.BIRTH_DATE,
 o.sex,
 o.DATE_ADDED,
 o.DATE_LAST_CHANGED,
 o.ADDED_BY,
 o.LAST_CHANGED_BY,
 o.KEY_INDICATOR

 ---NEED LAST RESEARCH REQUEST DATE

 ----NEED WEALTH SCREENING

 ----THEN CAN JOIN GIFTS, ACTIONS, SINCE LAST RESEARCH REQUEST DATE

 ------
 

FROM 
DBO.RECORDS AS O

WHERE 
((O.IS_CONSTITUENT  =  -1))    AND EXISTS (SELECT 
 RECORDS.ID "QRECID" FROM 
DBO.RECORDS AS RECORDS INNER JOIN DBO.ACTIONS AS RECORDS_ACTIONS ON RECORDS.ID = RECORDS_ACTIONS.RECORDS_ID WHERE 
((RECORDS_ACTIONS.TYPE  =  6336 AND RECORDS_ACTIONS.DTE >=  CAST('1/1/2017' AS DATETIME)))   AND O.ID  =  RECORDS.ID)

ORDER BY 
O.CONSTITUENT_ID