select 
pp.ID,
pp.PROSPECT_ID,
r.CONSTITUENT_ID,
case when r.ORG_NAME is null then CONCAT(r.FIRST_NAME,' ',r.LAST_NAME) else r.ORG_NAME end as CONSTITUENT_NAME,
CONCAT(sr.FIRST_NAME,' ',sr.LAST_NAME) as SOLICITOR_NAME,
pp.Proposal_Name as PROPOSAL_NAME,
pp.AMOUNT_ASKED,
pp.DATE_ASKED,
pp.AMOUNT_EXPECTED,
pp.DATE_EXPECTED,
pp.AMOUNT_FUNDED,
pp.DATE_FUNDED,

t1.LONGDESCRIPTION as PURPOSE,

t2.LONGDESCRIPTION as RATING,

t3.LONGDESCRIPTION as STATUS,

t4.LONGDESCRIPTION as REASON,


c.CAMPAIGN_ID


 from proposal as pp


left join PROPOSAL_SOLICITOR as ps on ps.PARENTID = pp.ID
left join TABLEENTRIES t1 on t1.TABLEENTRIESID = pp.PURPOSE
left join TABLEENTRIES t2 on t2.TABLEENTRIESID = pp.RATING
left join TABLEENTRIES t3 on t3.TABLEENTRIESID = pp.STATUS
left join TABLEENTRIES t4 on t4.TABLEENTRIESID = pp.REASON
left join records as sr on sr.ID = ps.SOLICITORID
left join PROSPECT as pr on pr.ID = pp.PROSPECT_ID
left join RECORDS as r on r.ID = pr.CONSTIT_ID
left join CAMPAIGN as c on c.ID = pp.CAMPAIGN
where --pp.STATUS = 5556

pp.DATE_Asked BETWEEN CAST('1/1/2018' AS DATETIME) AND '12/31/2018 23:59:59.997'
and ps.SOLICITORID = 86706